
const action_types = {
    LOGIN_USER: "LOGIN_USER",
    SET_LOGIN: "SET_LOGIN",
    GET_PRODUCT: "GET_PRODUCT",
    GET_PRODUCTS_BY_CATEGORY: "GET_PRODUCTS_BY_CATEGORY",
    SEARCH_PRODUCT: "SEARCH_PRODUCT",
    GET_CART: "GET_CART",
    GET_SINGLE_PRODUCT: "GET_SINGLE_PRODUCT",
}

export default action_types