
const action_types = {

    LOGIN_USER: "LOGIN_USER",
    SET_LOGIN: "SET_LOGIN",
    GET_PRODUCT: "GET_PRODUCT",
    REMOVE_PRODUCTS: "REMOVE_PRODUCTS",
    GET_PRODUCTS_BY_CATEGORY: "GET_PRODUCTS_BY_CATEGORY",
    SEARCH_PRODUCT: "SEARCH_PRODUCT",
    REMOVE_SEARCHED_PRODUCT: "REMOVE_SEARCHED_PRODUCT", 
    GET_SINGLE_PRODUCT: "GET_SINGLE_PRODUCT",
    REMOVE_SINGLE_PRODUCT: "REMOVE_SINGLE_PRODUCT",
    GET_CART_PRODUCTS: "GET_CART_PRODUCTS",
}

export default action_types 